/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiInput: typeof import('./src/components/OpenAiHuman/AiInput.vue')['default']
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    BrandSelectPopup: typeof import('./src/components/BrandSelectPopup/index.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    CareerPoster: typeof import('./src/components/Share/poster/CareerPoster.vue')['default']
    CareerPosters: typeof import('./src/components/Share/poster/CareerPosters.vue')['default']
    CarNumInput: typeof import('./src/components/carNumInput/carNumInput.vue')['default']
    CustomNavBar: typeof import('./src/components/customNavBar/index.vue')['default']
    ExchangeSheet: typeof import('./src/components/ExchangeSheet/ExchangeSheet.vue')['default']
    FormFile: typeof import('./src/components/FormFile.vue')['default']
    GetCode: typeof import('./src/components/GetCode/index.vue')['default']
    Givepresent: typeof import('./src/components/Share/poster/givepresent.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    Indexzs: typeof import('./src/components/Share/indexzs.vue')['default']
    MsgItem: typeof import('./src/components/OpenAiHuman/MsgItem.vue')['default']
    PageDurationTracker: typeof import('./src/components/PageDurationTracker.vue')['default']
    PrivacyDialog: typeof import('./src/components/PrivacyDialog/PrivacyDialog.vue')['default']
    ProductCard: typeof import('./src/components/integrate/ProductCard.vue')['default']
    ProductList: typeof import('./src/components/integrate/ProductList.vue')['default']
    ProductWaterfall: typeof import('./src/components/integrate/ProductWaterfall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SateLayer: typeof import('./src/components/SateLayer/index.vue')['default']
    SerAudioPlayer: typeof import('./src/components/ser-AudioPlayer/ser-AudioPlayer.vue')['default']
    SerCustomImageLoading: typeof import('./src/components/ser-CustomImageLoading/ser-CustomImageLoading.vue')['default']
    SerEmpty: typeof import('./src/components/ser-empty/ser-empty.vue')['default']
    SerNetwork: typeof import('./src/components/ser-empty/ser-network.vue')['default']
    Share: typeof import('./src/components/Share/index.vue')['default']
    Shopseckill: typeof import('./src/components/Share/poster/shopseckill.vue')['default']
    SingleVideoUploader: typeof import('./src/components/SingleVideoUploader.vue')['default']
    SpeechRecognition: typeof import('./src/components/SpeechRecognition.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Tool: typeof import('./src/components/waterfall/tool.ts')['default']
    Travel: typeof import('./src/components/home/travel.vue')['default']
    Travel2: typeof import('./src/components/home/travel2.vue')['default']
    Travel3: typeof import('./src/components/home/travel3.vue')['default']
    Travel4: typeof import('./src/components/home/travel4.vue')['default']
    Type: typeof import('./src/components/waterfall/type.ts')['default']
    UpdateProtocol: typeof import('./src/components/PrivacyDialog/UpdateProtocol.vue')['default']
    UseVoiceRecorder: typeof import('./src/components/MessageButton/useVoiceRecorder.ts')['default']
    Waterfall: typeof import('./src/components/waterfall/waterfall.vue')['default']
  }
}

// For TSX support
declare global {
  const AiInput: typeof import('./src/components/OpenAiHuman/AiInput.vue')['default']
  const AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
  const BrandSelectPopup: typeof import('./src/components/BrandSelectPopup/index.vue')['default']
  const Calendar: typeof import('./src/components/Calendar.vue')['default']
  const CareerPoster: typeof import('./src/components/Share/poster/CareerPoster.vue')['default']
  const CareerPosters: typeof import('./src/components/Share/poster/CareerPosters.vue')['default']
  const CarNumInput: typeof import('./src/components/carNumInput/carNumInput.vue')['default']
  const CustomNavBar: typeof import('./src/components/customNavBar/index.vue')['default']
  const ExchangeSheet: typeof import('./src/components/ExchangeSheet/ExchangeSheet.vue')['default']
  const FormFile: typeof import('./src/components/FormFile.vue')['default']
  const GetCode: typeof import('./src/components/GetCode/index.vue')['default']
  const Givepresent: typeof import('./src/components/Share/poster/givepresent.vue')['default']
  const ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
  const Indexzs: typeof import('./src/components/Share/indexzs.vue')['default']
  const MsgItem: typeof import('./src/components/OpenAiHuman/MsgItem.vue')['default']
  const PageDurationTracker: typeof import('./src/components/PageDurationTracker.vue')['default']
  const PrivacyDialog: typeof import('./src/components/PrivacyDialog/PrivacyDialog.vue')['default']
  const ProductCard: typeof import('./src/components/integrate/ProductCard.vue')['default']
  const ProductList: typeof import('./src/components/integrate/ProductList.vue')['default']
  const ProductWaterfall: typeof import('./src/components/integrate/ProductWaterfall.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SateLayer: typeof import('./src/components/SateLayer/index.vue')['default']
  const SerAudioPlayer: typeof import('./src/components/ser-AudioPlayer/ser-AudioPlayer.vue')['default']
  const SerCustomImageLoading: typeof import('./src/components/ser-CustomImageLoading/ser-CustomImageLoading.vue')['default']
  const SerEmpty: typeof import('./src/components/ser-empty/ser-empty.vue')['default']
  const SerNetwork: typeof import('./src/components/ser-empty/ser-network.vue')['default']
  const Share: typeof import('./src/components/Share/index.vue')['default']
  const Shopseckill: typeof import('./src/components/Share/poster/shopseckill.vue')['default']
  const SingleVideoUploader: typeof import('./src/components/SingleVideoUploader.vue')['default']
  const SpeechRecognition: typeof import('./src/components/SpeechRecognition.vue')['default']
  const ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
  const Tool: typeof import('./src/components/waterfall/tool.ts')['default']
  const Travel: typeof import('./src/components/home/travel.vue')['default']
  const Travel2: typeof import('./src/components/home/travel2.vue')['default']
  const Travel3: typeof import('./src/components/home/travel3.vue')['default']
  const Travel4: typeof import('./src/components/home/travel4.vue')['default']
  const Type: typeof import('./src/components/waterfall/type.ts')['default']
  const UpdateProtocol: typeof import('./src/components/PrivacyDialog/UpdateProtocol.vue')['default']
  const UseVoiceRecorder: typeof import('./src/components/MessageButton/useVoiceRecorder.ts')['default']
  const Waterfall: typeof import('./src/components/waterfall/waterfall.vue')['default']
}